### PR TITLE
Extra comment character was causing problems

### PR DESCRIPTION
**Pull request by konung**
Removed

### CODE REVIEW

**Comment by konung** [comment]
Sorry - looks like mine is a duplicate of issue #2 , didn't see it before.

**Comment by jarednova** [comment]
Fixed it -- thanks!

**Comment by konung** [comment]
Jared  Great plugin.

I have a separate question, just wondering how is your plugin different
from AmplyfyJS. I don't mean syntax diferences, but conceptually?

Thanks

On Mon, Oct 29, 2012 at 12:47 PM, Jared Novack notifications@github.comwrote:

> Fixed it -- thanks!
> 
> On Mon, Oct 29, 2012 at 1:42 PM, Nick Gorbikoff notifications@github.comwrote:
> 
> > Sorry - looks like mine is a duplicate of issue #2<
> > https://github.com/jarednova/jquery-total-storage/issues/2>, didn't see
> > it before.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/jarednova/jquery-total-storage/pull/3#issuecomment-9878217>.
> 
> ## 
> 
> Partner, Upstatement
> office: 617 329 1316
> cell: 314 368 0228
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jarednova/jquery-total-storage/pull/3#issuecomment-9878403.

## 

---

Nick Gorbikoff
nick.gorbikoff@gmail.com

**Comment by jarednova** [comment]
I'll confess I didn't know about AmplifyJS until now. It looks like a great
plugin/system. As for conceptual difference? I guess Amplify is a
more holistic problem/solution -- when I wrote this I was looking to solve
a more narrow problem.

**Pull request closed without merging**
